// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pirouette.Infrastructure;

#nullable disable

namespace Pirouette.Infrastructure.Migrations
{
    [DbContext(typeof(PirouetteDbContext))]
    [Migration("20260809150101_M1CoreEntities")]
    partial class M1CoreEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pirouette.Domain.ClassAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DanceClassId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("EffectiveFrom");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Until")
                        .HasColumnType("date")
                        .HasColumnName("EffectiveUntil");

                    b.HasKey("Id");

                    b.HasIndex("DanceClassId");

                    b.HasIndex("StudioId");

                    b.HasIndex("MemberId", "DanceClassId");

                    b.ToTable("ClassAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ClassAssignment_UntilNotBeforeFrom", "\"EffectiveUntil\" IS NULL OR \"EffectiveUntil\" >= \"EffectiveFrom\"");
                        });
                });

            modelBuilder.Entity("Pirouette.Domain.DanceClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Level")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("TermId");

                    b.HasIndex("StudioId", "TermId");

                    b.ToTable("DanceClasses", t =>
                        {
                            t.HasCheckConstraint("CK_DanceClass_AgeRangeOrdered", "\"MinimumAge\" IS NULL OR \"MaximumAge\" IS NULL OR \"MinimumAge\" <= \"MaximumAge\"");

                            t.HasCheckConstraint("CK_DanceClass_AgesNotNegative", "(\"MinimumAge\" IS NULL OR \"MinimumAge\" >= 0) AND (\"MaximumAge\" IS NULL OR \"MaximumAge\" >= 0)");

                            t.HasCheckConstraint("CK_DanceClass_CapacityPositive", "\"Capacity\" > 0");

                            t.HasCheckConstraint("CK_DanceClass_EndNotBeforeStart", "\"EndDate\" >= \"StartDate\"");
                        });
                });

            modelBuilder.Entity("Pirouette.Domain.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudioId", "Name");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("Pirouette.Domain.MeetingPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DanceClassId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DanceClassId");

                    b.HasIndex("StudioId");

                    b.ToTable("MeetingPatterns", null, t =>
                        {
                            t.HasCheckConstraint("CK_MeetingPattern_DoesNotCrossMidnight", "EXTRACT(EPOCH FROM \"StartTime\") + EXTRACT(EPOCH FROM \"Duration\") <= 86400");

                            t.HasCheckConstraint("CK_MeetingPattern_DurationPositive", "\"Duration\" > INTERVAL '0'");

                            t.HasCheckConstraint("CK_MeetingPattern_DurationWithinLimit", "\"Duration\" <= INTERVAL '8 hours'");
                        });
                });

            modelBuilder.Entity("Pirouette.Domain.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("StudioId", "LastName", "FirstName");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Pirouette.Domain.MemberRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("EffectiveFrom");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Until")
                        .HasColumnType("date")
                        .HasColumnName("EffectiveUntil");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "Role");

                    b.HasIndex("StudioId", "Role", "From");

                    b.ToTable("MemberRoles", null, t =>
                        {
                            t.HasCheckConstraint("CK_MemberRole_UntilNotBeforeFrom", "\"EffectiveUntil\" IS NULL OR \"EffectiveUntil\" >= \"EffectiveFrom\"");
                        });
                });

            modelBuilder.Entity("Pirouette.Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudioId", "Name");

                    b.ToTable("Rooms", t =>
                        {
                            t.HasCheckConstraint("CK_Room_CapacityPositive", "\"Capacity\" > 0");
                        });
                });

            modelBuilder.Entity("Pirouette.Domain.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Pirouette Dance Academy",
                            TimeZoneId = "America/New_York"
                        });
                });

            modelBuilder.Entity("Pirouette.Domain.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudioId", "Name");

                    b.ToTable("Terms", t =>
                        {
                            t.HasCheckConstraint("CK_Term_EndNotBeforeStart", "\"EndDate\" >= \"StartDate\"");
                        });
                });

            modelBuilder.Entity("Pirouette.Domain.ClassAssignment", b =>
                {
                    b.HasOne("Pirouette.Domain.DanceClass", null)
                        .WithMany("Assignments")
                        .HasForeignKey("DanceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pirouette.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pirouette.Domain.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Pirouette.Domain.DanceClass", b =>
                {
                    b.HasOne("Pirouette.Domain.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pirouette.Domain.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pirouette.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Pirouette.Domain.Household", b =>
                {
                    b.HasOne("Pirouette.Domain.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pirouette.Domain.MeetingPattern", b =>
                {
                    b.HasOne("Pirouette.Domain.DanceClass", null)
                        .WithMany("MeetingPatterns")
                        .HasForeignKey("DanceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pirouette.Domain.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pirouette.Domain.Member", b =>
                {
                    b.HasOne("Pirouette.Domain.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pirouette.Domain.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pirouette.Domain.MemberRole", b =>
                {
                    b.HasOne("Pirouette.Domain.Member", null)
                        .WithMany("Roles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pirouette.Domain.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pirouette.Domain.Room", b =>
                {
                    b.HasOne("Pirouette.Domain.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pirouette.Domain.Term", b =>
                {
                    b.HasOne("Pirouette.Domain.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pirouette.Domain.DanceClass", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("MeetingPatterns");
                });

            modelBuilder.Entity("Pirouette.Domain.Member", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
